services:
  postgres:
    image: postgres:14
    container_name: granja-patos-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: granja_de_patos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  flyway:
    image: flyway/flyway:latest
    container_name: flyway-migration
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["flyway", "migrate"]
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/granja_de_patos
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=12345678
    volumes:
      - ./migrations:/flyway/sql

volumes:
  pgdata: